--新增資料表>投票項目
DROP TABLE IF EXISTS ITEM;
CREATE TABLE ITEM(
ITEM_ID INT IDENTITY PRIMARY KEY,
NAME NVARCHAR(10)
);

--新增投票項目資料
INSERT INTO ITEM values(N'電腦'), (N'滑鼠')

--新增資料表>投票紀錄
DROP TABLE IF EXISTS RECORD;
CREATE TABLE RECORD(
ID INT IDENTITY PRIMARY KEY,
PERSON_NAME NVARCHAR(10),
ITEM_ID INT
);

--新增投票紀錄資料
INSERT INTO RECORD values('Leo', 1), ('Sandy', 1), ('Sandy', 2), ('Randy', 2), ('RSY', 2)
